language: node_js
node_js:
  - "7"
before_script:
  - npm install -g gulp-cli
script: gulp
after_script: "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"
cache:
  directories:
    - "node_modules"